/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { InventoryManager } from "./InventoryManager";
import { InventoryManagerCountArgs } from "./InventoryManagerCountArgs";
import { InventoryManagerFindManyArgs } from "./InventoryManagerFindManyArgs";
import { InventoryManagerFindUniqueArgs } from "./InventoryManagerFindUniqueArgs";
import { DeleteInventoryManagerArgs } from "./DeleteInventoryManagerArgs";
import { InventoryManagerService } from "../inventoryManager.service";
@graphql.Resolver(() => InventoryManager)
export class InventoryManagerResolverBase {
  constructor(protected readonly service: InventoryManagerService) {}

  async _inventoryManagersMeta(
    @graphql.Args() args: InventoryManagerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [InventoryManager])
  async inventoryManagers(
    @graphql.Args() args: InventoryManagerFindManyArgs
  ): Promise<InventoryManager[]> {
    return this.service.inventoryManagers(args);
  }

  @graphql.Query(() => InventoryManager, { nullable: true })
  async inventoryManager(
    @graphql.Args() args: InventoryManagerFindUniqueArgs
  ): Promise<InventoryManager | null> {
    const result = await this.service.inventoryManager(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => InventoryManager)
  async deleteInventoryManager(
    @graphql.Args() args: DeleteInventoryManagerArgs
  ): Promise<InventoryManager | null> {
    try {
      return await this.service.deleteInventoryManager(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
