/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { InteriorDesigner } from "./InteriorDesigner";
import { InteriorDesignerCountArgs } from "./InteriorDesignerCountArgs";
import { InteriorDesignerFindManyArgs } from "./InteriorDesignerFindManyArgs";
import { InteriorDesignerFindUniqueArgs } from "./InteriorDesignerFindUniqueArgs";
import { DeleteInteriorDesignerArgs } from "./DeleteInteriorDesignerArgs";
import { InteriorDesignerService } from "../interiorDesigner.service";
@graphql.Resolver(() => InteriorDesigner)
export class InteriorDesignerResolverBase {
  constructor(protected readonly service: InteriorDesignerService) {}

  async _interiorDesignersMeta(
    @graphql.Args() args: InteriorDesignerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [InteriorDesigner])
  async interiorDesigners(
    @graphql.Args() args: InteriorDesignerFindManyArgs
  ): Promise<InteriorDesigner[]> {
    return this.service.interiorDesigners(args);
  }

  @graphql.Query(() => InteriorDesigner, { nullable: true })
  async interiorDesigner(
    @graphql.Args() args: InteriorDesignerFindUniqueArgs
  ): Promise<InteriorDesigner | null> {
    const result = await this.service.interiorDesigner(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => InteriorDesigner)
  async deleteInteriorDesigner(
    @graphql.Args() args: DeleteInteriorDesignerArgs
  ): Promise<InteriorDesigner | null> {
    try {
      return await this.service.deleteInteriorDesigner(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
