/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SupervisorService } from "../supervisor.service";
import { SupervisorCreateInput } from "./SupervisorCreateInput";
import { Supervisor } from "./Supervisor";
import { SupervisorFindManyArgs } from "./SupervisorFindManyArgs";
import { SupervisorWhereUniqueInput } from "./SupervisorWhereUniqueInput";
import { SupervisorUpdateInput } from "./SupervisorUpdateInput";

export class SupervisorControllerBase {
  constructor(protected readonly service: SupervisorService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Supervisor })
  async createSupervisor(
    @common.Body() data: SupervisorCreateInput
  ): Promise<Supervisor> {
    return await this.service.createSupervisor({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Supervisor] })
  @ApiNestedQuery(SupervisorFindManyArgs)
  async supervisors(@common.Req() request: Request): Promise<Supervisor[]> {
    const args = plainToClass(SupervisorFindManyArgs, request.query);
    return this.service.supervisors({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Supervisor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async supervisor(
    @common.Param() params: SupervisorWhereUniqueInput
  ): Promise<Supervisor | null> {
    const result = await this.service.supervisor({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Supervisor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSupervisor(
    @common.Param() params: SupervisorWhereUniqueInput,
    @common.Body() data: SupervisorUpdateInput
  ): Promise<Supervisor | null> {
    try {
      return await this.service.updateSupervisor({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Supervisor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSupervisor(
    @common.Param() params: SupervisorWhereUniqueInput
  ): Promise<Supervisor | null> {
    try {
      return await this.service.deleteSupervisor({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
