/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Supervisor } from "./Supervisor";
import { SupervisorCountArgs } from "./SupervisorCountArgs";
import { SupervisorFindManyArgs } from "./SupervisorFindManyArgs";
import { SupervisorFindUniqueArgs } from "./SupervisorFindUniqueArgs";
import { DeleteSupervisorArgs } from "./DeleteSupervisorArgs";
import { SupervisorService } from "../supervisor.service";
@graphql.Resolver(() => Supervisor)
export class SupervisorResolverBase {
  constructor(protected readonly service: SupervisorService) {}

  async _supervisorsMeta(
    @graphql.Args() args: SupervisorCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Supervisor])
  async supervisors(
    @graphql.Args() args: SupervisorFindManyArgs
  ): Promise<Supervisor[]> {
    return this.service.supervisors(args);
  }

  @graphql.Query(() => Supervisor, { nullable: true })
  async supervisor(
    @graphql.Args() args: SupervisorFindUniqueArgs
  ): Promise<Supervisor | null> {
    const result = await this.service.supervisor(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Supervisor)
  async deleteSupervisor(
    @graphql.Args() args: DeleteSupervisorArgs
  ): Promise<Supervisor | null> {
    try {
      return await this.service.deleteSupervisor(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
