/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { FinanceManager } from "./FinanceManager";
import { FinanceManagerCountArgs } from "./FinanceManagerCountArgs";
import { FinanceManagerFindManyArgs } from "./FinanceManagerFindManyArgs";
import { FinanceManagerFindUniqueArgs } from "./FinanceManagerFindUniqueArgs";
import { DeleteFinanceManagerArgs } from "./DeleteFinanceManagerArgs";
import { FinanceManagerService } from "../financeManager.service";
@graphql.Resolver(() => FinanceManager)
export class FinanceManagerResolverBase {
  constructor(protected readonly service: FinanceManagerService) {}

  async _financeManagersMeta(
    @graphql.Args() args: FinanceManagerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [FinanceManager])
  async financeManagers(
    @graphql.Args() args: FinanceManagerFindManyArgs
  ): Promise<FinanceManager[]> {
    return this.service.financeManagers(args);
  }

  @graphql.Query(() => FinanceManager, { nullable: true })
  async financeManager(
    @graphql.Args() args: FinanceManagerFindUniqueArgs
  ): Promise<FinanceManager | null> {
    const result = await this.service.financeManager(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => FinanceManager)
  async deleteFinanceManager(
    @graphql.Args() args: DeleteFinanceManagerArgs
  ): Promise<FinanceManager | null> {
    try {
      return await this.service.deleteFinanceManager(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
