/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DispatchManager } from "./DispatchManager";
import { DispatchManagerCountArgs } from "./DispatchManagerCountArgs";
import { DispatchManagerFindManyArgs } from "./DispatchManagerFindManyArgs";
import { DispatchManagerFindUniqueArgs } from "./DispatchManagerFindUniqueArgs";
import { DeleteDispatchManagerArgs } from "./DeleteDispatchManagerArgs";
import { DispatchManagerService } from "../dispatchManager.service";
@graphql.Resolver(() => DispatchManager)
export class DispatchManagerResolverBase {
  constructor(protected readonly service: DispatchManagerService) {}

  async _dispatchManagersMeta(
    @graphql.Args() args: DispatchManagerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [DispatchManager])
  async dispatchManagers(
    @graphql.Args() args: DispatchManagerFindManyArgs
  ): Promise<DispatchManager[]> {
    return this.service.dispatchManagers(args);
  }

  @graphql.Query(() => DispatchManager, { nullable: true })
  async dispatchManager(
    @graphql.Args() args: DispatchManagerFindUniqueArgs
  ): Promise<DispatchManager | null> {
    const result = await this.service.dispatchManager(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DispatchManager)
  async deleteDispatchManager(
    @graphql.Args() args: DeleteDispatchManagerArgs
  ): Promise<DispatchManager | null> {
    try {
      return await this.service.deleteDispatchManager(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
