/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { QuoteService } from "../quote.service";
import { QuoteCreateInput } from "./QuoteCreateInput";
import { Quote } from "./Quote";
import { QuoteFindManyArgs } from "./QuoteFindManyArgs";
import { QuoteWhereUniqueInput } from "./QuoteWhereUniqueInput";
import { QuoteUpdateInput } from "./QuoteUpdateInput";

export class QuoteControllerBase {
  constructor(protected readonly service: QuoteService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Quote })
  async createQuote(@common.Body() data: QuoteCreateInput): Promise<Quote> {
    return await this.service.createQuote({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Quote] })
  @ApiNestedQuery(QuoteFindManyArgs)
  async quotes(@common.Req() request: Request): Promise<Quote[]> {
    const args = plainToClass(QuoteFindManyArgs, request.query);
    return this.service.quotes({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Quote })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async quote(
    @common.Param() params: QuoteWhereUniqueInput
  ): Promise<Quote | null> {
    const result = await this.service.quote({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Quote })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateQuote(
    @common.Param() params: QuoteWhereUniqueInput,
    @common.Body() data: QuoteUpdateInput
  ): Promise<Quote | null> {
    try {
      return await this.service.updateQuote({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Quote })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteQuote(
    @common.Param() params: QuoteWhereUniqueInput
  ): Promise<Quote | null> {
    try {
      return await this.service.deleteQuote({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
