/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Help } from "./Help";
import { HelpCountArgs } from "./HelpCountArgs";
import { HelpFindManyArgs } from "./HelpFindManyArgs";
import { HelpFindUniqueArgs } from "./HelpFindUniqueArgs";
import { DeleteHelpArgs } from "./DeleteHelpArgs";
import { HelpService } from "../help.service";
@graphql.Resolver(() => Help)
export class HelpResolverBase {
  constructor(protected readonly service: HelpService) {}

  async _helpsMeta(
    @graphql.Args() args: HelpCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Help])
  async helps(@graphql.Args() args: HelpFindManyArgs): Promise<Help[]> {
    return this.service.helps(args);
  }

  @graphql.Query(() => Help, { nullable: true })
  async help(@graphql.Args() args: HelpFindUniqueArgs): Promise<Help | null> {
    const result = await this.service.help(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Help)
  async deleteHelp(@graphql.Args() args: DeleteHelpArgs): Promise<Help | null> {
    try {
      return await this.service.deleteHelp(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
